from pathlib import Path
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from PIL import Image as PIL
import os, json
REPO=Path(__file__).resolve().parents[1]
ROOT=Path(os.environ.get('SAWSTAR_MANUAL_OUTPUT', str(REPO/'build-manuals')))
(ROOT/'tmp/pdfs').mkdir(parents=True,exist_ok=True)
(ROOT/'output/pdf').mkdir(parents=True,exist_ok=True)
METADATA=json.loads((REPO/'release.json').read_text())
VERSION=METADATA['version']
CANDIDATE=METADATA.get('candidate', '')
EDITION=METADATA.get('release_date') or os.environ.get('SAWSTAR_MANUAL_DATE', 'development')
EDITION_LABEL=VERSION + ('-' + CANDIDATE if CANDIDATE else '')
F=Path(os.environ.get('SAWSTAR_MANUAL_FONTS','/usr/share/fonts/truetype/dejavu'))
for n,f in [('DV','DejaVuSans.ttf'),('DVB','DejaVuSans-Bold.ttf')]: pdfmetrics.registerFont(TTFont(n,str(F/f)))
pdfmetrics.registerFontFamily('DV',normal='DV',bold='DVB',italic='DV',boldItalic='DVB')
S=getSampleStyleSheet()
S.add(ParagraphStyle(name='Body',fontName='DV',fontSize=10,leading=15,spaceAfter=9,textColor=colors.HexColor('#283642')))
S.add(ParagraphStyle(name='Title2',fontName='DVB',fontSize=25,leading=30,spaceAfter=18,textColor=colors.HexColor('#163c55')))
S.add(ParagraphStyle(name='Sub',fontName='DVB',fontSize=12,leading=17,spaceBefore=12,spaceAfter=7,textColor=colors.HexColor('#16719b')))
S.add(ParagraphStyle(name='Small2',fontName='DV',fontSize=8,leading=11,spaceAfter=7,textColor=colors.HexColor('#526573')))
# Use supplied screenshots unchanged; ReportLab scales them on the page.
import shutil
for n in ['main','advanced','presets']:
    shutil.copy2(REPO/f'docs/reference/screenshot-{n}.png',ROOT/f'tmp/pdfs/{n}.png')
EN=[
('Start here',[
('About this guide',f'SAWSTAR is a VST3 synthesizer for saw leads, pads, plucks and related sounds. This guide describes SAWSTAR {EDITION_LABEL} and its 24 embedded factory presets. Edition: {EDITION} Screenshots retain the original 1.0.1 preview capture labels; preset counts and library contents can differ.'),
('Reading the interface','Names such as MAIN, ADVANCED, PRESETS, Save As and NOISE COLOR are the labels to look for in the plugin. Start with MAIN for sound design; ADVANCED contains performance and deeper controls; PRESETS manages the library and explains saved sounds.'),
('Contents','2 Installation and first sound • 3 Navigation and controls • 4 Sound sources and output • 5 Filter, envelopes and scope • 6 Effects • 7 Performance and arpeggiator • 8 LFO and modulation • 9 Preset workflow • 10 Factory library • 11 Sound design recipes • 12 Troubleshooting and support • 13 Performance details')]),
('Installation and first sound',[
('Choose the correct package','Choose Windows x64 or native ARM64 to match your DAW. macOS Universal includes Intel and Apple Silicon. Only VST3 is supplied. Windows needs an OpenGL 2-capable driver; macOS uses Metal. Build targets are Windows 10 x64, Windows 11 ARM64 and macOS 11; these are not verified minimum-system guarantees. No separate DirectX or Visual C++ Redistributable is required.'),
('Install','Close your DAW before replacing the plugin, and keep the previous bundle as a backup. Run the Windows Setup EXE, or open the macOS DMG and run its PKG. Administrator authorization is required. macOS installs to /Library/Audio/Plug-Ins/VST3/; Windows installs to C:\\Program Files\\Common Files\\VST3\\ . Move older user-local Mac copies outside VST3 folders to avoid duplicates. Restart the host and rescan plugins if required. Do not copy only the executable from inside the bundle.'),
('Unsigned packages','macOS packages have no Apple Developer ID signature or notarization; Windows installers are not Authenticode signed. Security warnings may appear. Follow the package INSTALLATION guide and approve only the trusted SAWSTAR download. Do not disable system-wide protections.'),
('First sound in REAPER','Insert SAWSTAR as an instrument on a track. Click a key on its onscreen keyboard. For an external keyboard, choose the track MIDI input, arm the track and enable input monitoring as appropriate. Check that the track and master are unmuted and routed to your audio device. Select SuperSaw One in the top preset selector and play a few notes.'),
('Updating safely','Back up user presets and important projects before updating the plugin. Check the About build information after restarting the DAW: an open host may retain the old plugin. Factory presets are embedded and need no separate bank installation.')]),
('Navigation and controls',[
('Three views, one instrument','MAIN, ADVANCED and PRESETS share the top preset selector and the bottom keyboard, wheels and status strip. Switching views does not load a different sound. The preset selector and its arrows change the loaded preset. The gear menu provides interface scaling, the downloads link and About; OK closes About.'),
('Editing a sound','Drag knobs and faders to change values. Use the value-entry field where available for an exact number; confirm the entry with Enter. Dropdown controls choose an option. The blue active state distinguishes enabled switches from their darker inactive state. Changing a control affects the sound immediately; save the sound if you want to keep it.'),
('Keyboard and wheels','The compact keyboard covers MIDI notes 36-96; the host can send the full MIDI note range. There is no octave-switch control for the onscreen keyboard. PITCH springs back to center when released. MOD retains its position. Double-click either wheel to reset it. The GUI keyboard and wheels use MIDI channel 1; external MIDI controller processing is channel-aware.'),
('What is saved','Sound parameters belong to presets and DAW state. Wheel positions are temporary MIDI controller values: record wheel movements as MIDI in your DAW. The footer reports sample rate, active voices and CPU information. These are status indicators, not fixed performance promises.')]),
('Sound sources and output',[
('OSC 1 and OSC 2','Choose Saw, Square, Triangle or Sine in the waveform selector. OCT transposes the oscillator by octaves. DETUNE spreads the side oscillators. UNISON blends six detuned side oscillators with the central oscillator; it is not a polyphony selector. At zero, the center dominates. WIDTH spreads the unison across stereo. Start with a saw, moderate UNISON and a small DETUNE value, then adjust by ear.'),
('SUB and MIXER','SUB offers Sine, Triangle and Square with a lower octave range. Its volume is controlled by the SUB mixer fader. The four mixer faders balance OSC 1, OSC 2, SUB and NOISE. A waveform can be configured but remain inaudible if its mixer level is zero.'),
('Noise','Choose White, Pink or Dark noise below the mixer. White is bright and broad, Pink emphasizes lower frequencies relative to White, and Dark provides a darker character. NOISE COLOR further shapes the tone: negative values darken it and positive values brighten it by reducing low-frequency content. The NOISE fader controls how much noise enters the sound.'),
('OUTPUT','VOLUME sets the master output level; BOOST adds gain. Watch the output meter and listen while balancing loud presets. WIDE and its AMOUNT expand existing stereo separation after the effects; they do not create stereo from a mono signal. Oscillator WIDTH works earlier in the signal path. Check mono compatibility when using wide sounds. Internal peak protection does not guarantee that later DAW effects or summed tracks will never clip.')]),
('Filter, envelopes and scope',[
('FILTER','Choose Low Pass 12, Low Pass 24, High Pass 12 or Band Pass 12. CUTOFF sets the filter frequency, RES emphasizes the cutoff region and DRIVE adds filter character. FILTER MIX blends the filtering into the sound: at zero, a cutoff change may be inaudible. KEY TRACK makes cutoff follow played pitch. The cutoff display is an illustration of the filter setting.'),
('Two envelopes','AMP ENV controls the loudness of each note. A is attack time, D is decay time, S is the held sustain level, and R is release time after letting go. FILTER ENV has its own ADSR and AMOUNT: positive amount opens the filter, negative amount moves it in the opposite direction. A short decay and low sustain are useful for plucks; longer attack and release suit pads.'),
('Realtime waveform','The green scope below AMP ENV shows the summed voice signal before effects, master width and output gain. Its horizontal axis is time; the center line is zero amplitude, not 0 Hz. The dark grid and triggered display help reveal waveform structure. The display scales amplitude automatically, so it is not a calibrated loudness meter.'),
('Interpreting the trace','A single periodic note is easier to read than a detuned chord or noise. A complex moving trace is normal for those sounds. Stereo is combined for this display, so cancellation can reduce the trace. Changing OUTPUT or adding delay will not change this pre-effects view. The scope is visual only and does not process the audible signal.')]),
('Effects',[
('Signal order','The voice signal reaches Chorus, then Delay, then Reverb, followed by master stereo width and output processing. The MAIN FX section provides the quick controls; open the corresponding effect on ADVANCED for detailed settings. Enable an effect and raise its MIX to hear it.'),
('Chorus','Chorus adds movement and thickness using a modulated delayed signal. MIX balances wet and dry sound. RATE controls movement speed and DEPTH its extent. For a steady lead, use a modest mix and slow rate; excessive depth can make pitch movement more obvious.'),
('Delay','MIX sets the echo level. TIME selects milliseconds in free mode; tempo sync uses a musical DIVISION and the host tempo. FEEDBACK sets the number and persistence of repeats, while TONE darkens or brightens them. Stereo and Ping Pong modes give different spatial patterns. Lower feedback and mix if echoes obscure the next phrase.'),
('Reverb','MIX adds the reverberant signal. SIZE changes the space character, DECAY controls tail duration and DAMPING shapes the high-frequency decay. Use shorter, quieter reverb for rhythmic plucks and more space for pads. Long release, delay feedback and reverb tails can all continue after a key is released; this is not automatically a stuck-note fault.')]),
('Performance and arpeggiator',[
('Voice modes and glide','Poly plays chords with up to 16 synth voices. Mono and Legato are single-note performance modes; Legato suits connected phrases. GLIDE controls the transition between pitches. Its mode can apply it always or only when notes overlap. PITCH BEND range is adjustable up to 24 semitones; MOD DEPTH controls the built-in modulation-wheel route to cutoff.'),
('Build an arpeggio','Enable ARP and hold a chord. ORDER chooses Up, Down, Up/Down, Random or Played. Played follows key order. RATE selects the musical step length; OCTAVES extends the pattern across 1-4 octaves. GATE controls how much of a step the note lasts. SWING alternates longer and shorter steps.'),
('HOLD','HOLD latches the chord after your fingers leave the keys. After all physical keys are released, playing a new chord replaces the latched phrase. Disable HOLD to stop relying on the latch; sustain-pedal behavior can still affect held notes. Disable ARP to return to ordinary playing.'),
('Tempo behavior','The first held key starts the phrase. The arp follows host BPM but is not an absolute song-grid sequencer. It can play while the host is stopped; stopping a running host clears the phrase, and a new key starts it again. Generated notes drive SAWSTAR internally; the arp is not presented as a MIDI-output or programmable step-sequencer feature.')]),
('LFO and modulation',[
('Two independent LFOs','LFO 1 / LFO 2 selects which LFO you edit; both can operate simultaneously. Choose Sine, Triangle, Ramp or Square. RATE uses free frequency or tempo-synced division. Retrigger restarts the phase on the first key; free phase keeps it moving. The direct destination can be cutoff, pitch, amplitude or pan. AMOUNT sets the direct route depth.'),
('Four modulation rows','Each row selects a source, a destination and a signed amount. Sources are Off, LFO 1, LFO 2, Mod Wheel, Velocity and Aftertouch. Destinations include Filter Cutoff, Pitch, Amp Level, Pan and Noise Color. Negative amount reverses the direction. Aftertouch means MIDI channel pressure; polyphonic key pressure and MPE are not supplied here.'),
('Avoid accidental double modulation','An LFO matrix source is taken before its direct AMOUNT. Therefore, setting direct AMOUNT to zero does not silence an active matrix route. Multiple routes add together. MOD DEPTH provides a separate built-in wheel-to-cutoff route, even when all matrix rows are Off. Wheel down adds zero cutoff offset: it is the preset baseline, not an incorrect or incomplete sound. Raising the wheel opens the filter according to MOD DEPTH. A Mod Wheel matrix row adds its own effect on top. Set MOD DEPTH to zero if the matrix should provide the only wheel assignment.'),
('Peak meter','The stereo sample-peak meter has a one-second peak hold. CLIP lights indicate output samples reaching 0 dBFS. Click to clear, or wait five seconds after the last clip. Output protection normally prevents clipping. This is not RMS or true-peak metering.'),
('A subtle pad example','Select a pad. Set LFO 2 to a slow sine, with direct AMOUNT zero. In one matrix row choose LFO 2, Pan and a small positive amount. Listen in stereo, then reduce the row amount to compare. Save As preserves the result as a new user preset.')]),
('Preset workflow',[
('Browse and understand','Click a preset row to load it. Category and search filters narrow the list without changing the sound by themselves. Search matches names, categories and tags. The heart marks a favorite. HOW IT WORKS shows the saved preset settings, not your unsaved edits; it updates when the edited sound is saved.'),
('Save and Save As','Save overwrites the active changed user preset after confirmation. Factory presets and templates are read-only: use Save As to create a user copy. Save As opens a naming/file dialog and creates a new .sawstar file; use a different name when a file already exists. An externally saved file is also copied into the managed library when possible. A collision can prevent that library copy.'),
('Import, Copy and Paste','Import accepts multiple .sawstar files at once, so a collection need not be imported one file at a time. It reports skipped or failed items and does not automatically play a preset. Copy/Paste transfers sound settings within the editor and creates no file until saved. This clipboard is temporary and is cleared when the editor closes.'),
('Rename, Delete and Initialize','Rename changes a selected user preset name. Delete asks for confirmation and retains a .deleted backup; it does not stop the currently playing sound. Initialize asks before resetting the sound to Init. Save changes you want to keep before initializing or loading another sound.'),
('Library and recovery','User files: macOS ~/Library/Application Support/SAWSTAR/Presets ; Windows %APPDATA%\\SAWSTAR\\Presets . Save backups are kept in .sawstar-backups below that folder. Restore a backup by copying it into the library under an unused .sawstar filename. DAW projects store sound parameters independently, but may not restore the association with a user file for Save; reload that user preset to re-establish it.')]),
('Factory library: 24 starting points',[
('Seven Templates','Init • Pad-Init • Lead-Init • Pluck-Init • Bass-Init • Keys-Init • Arp-Init. These are deliberate starting points rather than finished demonstrations. Effects and movement are kept off. In Arp-Init, enable ARP yourself to begin developing a pattern.'),
('Leads','Wide Saw Lead • SuperSaw One • Silk Lead • Solid Saw Lead. Explore stereo unison, fuller saw layers and connected lead playing. Compare with Lead-Init to understand which changes create the finished character.'),
('Pads','Soft Pad • Soft Pad One • Warm Horizon • Velvet Pad. Use held chords to hear envelope development and tails. Keep space for other instruments when adding width and reverb.'),
('Plucks, basses and keys','Plucks: Saw Pluck • Glass Pluck • Trance Pluck. Basses: Deep Bass • Round Sub. Keys: Bright Keys • Air Keys. Try short and long notes, plus different velocities, to understand the envelope response.'),
('Arpeggiated sounds','Simple Steps • Octave Steps. Hold a chord and explore rate and gate before changing the oscillators. Empty categories in the browser do not indicate a missing installation; this edition contains the 24 named presets above. User presets are additional and are not part of the embedded factory count.')]),
('Three sound design exercises',[
('A broad lead','Load Lead-Init. Choose Saw for OSC 1, raise UNISON gradually and use moderate DETUNE. Bring in OSC 2 at a lower mixer level to add body. Adjust WIDTH while checking mono. Use a fast amp attack and a release that does not overlap phrases too much. Add a restrained delay, then balance OUTPUT against another instrument. Save As with your own name.'),
('A soft pad','Load Pad-Init. Blend two oscillators and lengthen amp attack and release. Lower cutoff with FILTER MIX active, and use a gentle filter-envelope amount. Add a small chorus and reverb. If needed, introduce a very slow, low-depth pan or cutoff LFO. Avoid adding modulation only because it is available: a stable pad is a valid design.'),
('A clear pluck','Load Pluck-Init. Use a short filter-envelope decay, low sustain and a positive filter amount. Match the amp envelope to the desired note length. Add a quiet tempo-synced delay and little reverb so the attack remains clear. Play repeated notes at the song tempo before saving.'),
('Compare fairly','A louder setting can seem more impressive without being better. Match output levels when comparing variants. Change one section at a time, save useful variations, and use HOW IT WORKS to revisit the saved signal-path choices.')]),
('Troubleshooting and support',[
('No sound','Check host audio output, track routing and monitoring, mixer source levels and OUTPUT. Disable ARP/HOLD for a simple key test. A filter with very low cutoff and full mix can strongly attenuate the sound. Try Init or a known factory preset.'),
('A control seems ineffective','Check the relevant enable switch and MIX. DETUNE and WIDTH have little audible effect when unison side voices are not mixed in. WIDE needs stereo content. The scope is before effects. HOW IT WORKS follows saved settings. An LFO may act through a matrix row even with its direct amount at zero.'),
('A sound continues','Check amp release, sustain pedal, ARP HOLD, delay feedback and reverb decay. If sound continues unexpectedly after these are cleared, stop playback and reload the instrument in a test project. Report the exact preset, MIDI sequence, host and build information rather than overwriting an important project.'),
('Preset or display issue','Clear search/category filters if a preset seems missing. Reload a user preset before Save if its association was lost after project recall. Try another GUI scale if the window does not fit. Reopen the editor after an update, and verify the About build. Imported malformed or conflicting files can be skipped; read the import result.'),
('Project and credits','SAWSTAR: Simple Synth - Big Sound. The Sounds of Trance. Created by Gyuricza Róbert / RobCZart82. Project, source and issue reporting: https://github.com/RobCZart82/SAWSTAR . The project license and third-party notices are supplied in the repository. See the release notes for download packages and supported configurations.')])]
HU=[
('Kezdjük itt',[
('Az útmutatóról',f'A SAWSTAR VST3 szintetizátor saw lead, pad, pluck és rokon hangszínek készítésére. Ez az útmutató a SAWSTAR {EDITION_LABEL} változatot és annak 24 beépített factory presetjét ismerteti. Kiadás: {EDITION} A képeken megmaradtak az eredeti 1.0.1 előzetes felvételi címkék; a presetek száma és a könyvtár tartalma eltérhet.'),
('A felület olvasása','A MAIN, ADVANCED, PRESETS, Save As és NOISE COLOR neveket a programban is így találod. A MAIN a hangkészítésé, az ADVANCED a részletesebb és előadási beállításoké, a PRESETS pedig a hangszínkönyvtáré és a mentett hangok magyarázatáé.'),
('Tartalom','2 Telepítés és első hang • 3 Nézetek és kezelőszervek • 4 Hangforrások és kimenet • 5 Szűrő, burkolók és scope • 6 Effektek • 7 Előadás és arpeggiator • 8 LFO és moduláció • 9 Presetek kezelése • 10 Factory könyvtár • 11 Hangkészítési gyakorlatok • 12 Hibaelhárítás és támogatás • 13 Játék és vezérlők')]),
('Telepítés és első hang',[
('A megfelelő csomag','A Windows x64 vagy natív ARM64 csomagot a DAW-hoz válaszd. A macOS Universal Intel és Apple Silicon kódot tartalmaz. Csak VST3 készül. Windows alatt OpenGL 2 illesztőprogram, macOS-en Metal szükséges. A build célja Windows 10 x64, Windows 11 ARM64 és macOS 11; ezek nem igazolt minimumok. Külön DirectX vagy Visual C++ Redistributable nem szükséges.'),
('Telepítés','A csere előtt zárd be a DAW-ot, és őrizd meg az előző plugint. Futtasd a Windows Setup EXE-t, vagy a macOS DMG-ben lévő PKG-t. Rendszergazdai jóváhagyás szükséges. Telepítési hely: macOS /Library/Audio/Plug-Ins/VST3/; Windows C:\\Program Files\\Common Files\\VST3\\ . A korábbi felhasználói Mac példányt helyezd a VST3 mappákon kívüli biztonsági másolatba. Indítsd újra a DAW-ot, és szükség esetén indíts plugin-újrakeresést. Ne csak a csomag belsejében lévő programfájlt másold át.'),
('Aláírás nélküli csomagok','A macOS csomagon nincs Apple Developer ID aláírás vagy notarizáció; a Windows telepítő sem Authenticode-aláírt. Biztonsági figyelmeztetés megjelenhet. Kövesd a csomag INSTALLATION útmutatóját, és csak a megbízható SAWSTAR letöltést engedélyezd. A rendszer egészének védelmét ne kapcsold ki.'),
('Első hang REAPER-ben','Szúrj be egy SAWSTAR hangszert egy sávra. Kattints a plugin zongorabillentyűjére. Külső billentyűzethez válaszd ki a sáv MIDI bemenetét, élesítsd a sávot, és szükség szerint kapcsold be a bemenet hallgatását. A sáv és a master ne legyen némítva, és legyen megfelelő hangkimenet. A felső presetválasztóban töltsd be a SuperSaw One hangot, majd játssz néhány hangot.'),
('Frissítés','Frissítés előtt mentsd el a user preseteket és a fontos projekteket. Újraindítás után az About buildadataival ellenőrizd a verziót: a nyitva maradt DAW a régi plugint tarthatja memóriában. A factory presetek be vannak építve, nem igényelnek külön banktelepítést.')]),
('Nézetek és kezelőszervek',[
('Három nézet, egy hangszer','A MAIN, ADVANCED és PRESETS közös felső presetválasztót és alsó billentyűzetet, kerekeket, állapotsort használ. A nézetváltás nem tölt be másik hangot. A felső presetválasztó és nyilai viszont hangszínt váltanak. A fogaskerék menüjében méretezés, letöltési hivatkozás és About található; az About ablakot az OK zárja be.'),
('Értékek módosítása','A potmétereket és fadereket húzással állíthatod. Ahol elérhető, az értékmezőben pontos számot adhatsz meg; Enterrel fogadd el. A lenyíló mezők lehetőségeket választanak. A bekapcsolt állapot kék, a kikapcsolt sötétebb. A változás azonnal hat a hangra; menteni kell, ha később is meg akarod tartani.'),
('Billentyűzet és kerekek','A kompakt billentyűzet a 36-96 MIDI hangokat éri el; a DAW a teljes MIDI hangtartományt küldheti. Külön oktávváltó nincs. A PITCH elengedéskor középre tér vissza, a MOD megtartja a helyzetét. Dupla kattintással mindkettő alaphelyzetbe áll. A GUI billentyűzete és kerekei az 1-es MIDI csatornát használják; a külső vezérlők feldolgozása csatornánként történik.'),
('Mi kerül mentésre?','A hangparamétereket a preset és a DAW állapota tárolja. A kerekek helyzete átmeneti MIDI vezérlés: a mozgásukat MIDI-ként rögzítsd a DAW-ban. Alul a mintavételi frekvencia, az aktív hangok és a CPU adatai láthatók. Ezek állapotjelzések, nem állandó teljesítményígéretek.')]),
('Hangforrások és kimenet',[
('OSC 1 és OSC 2','A hullámformaválasztó Saw, Square, Triangle és Sine lehetőséget ad. Az OCT oktávokkal transzponál. A DETUNE széthangolja az oldalsó oszcillátorokat. Az UNISON hat oldalsó oszcillátort kever a központihoz; nem a polifónia számát állítja. Nulla értéknél a központi hang dominál. A WIDTH sztereóban széthúzza a unisont. Kezdj saw hullámmal, mérsékelt UNISON és kis DETUNE értékkel, majd hallás alapján finomíts.'),
('SUB és MIXER','A SUB Sine, Triangle és Square hullámot kínál, mélyebb oktávtartományban. Hangerejét a mixer SUB fadere állítja. A négy mixerfader az OSC 1, OSC 2, SUB és NOISE arányát szabályozza. Egy beállított oszcillátor is néma marad, ha a mixerben nulla a szintje.'),
('Zaj','A mixer alatt White, Pink vagy Dark zajt választhatsz. A White világos és széles spektrumú, a Pink a White-hoz képest nagyobb súlyt ad a mély tartománynak, a Dark sötétebb karakterű. A NOISE COLOR tovább alakítja: negatív irányban sötétít, pozitív irányban a mélyek csökkentésével világosít. A zaj mennyiségét a NOISE fader adja.'),
('OUTPUT','A VOLUME a kimeneti szint, a BOOST további erősítés. Hangszínek összehasonlításakor figyeld a mérőt és a hallott hangerőt. A WIDE és AMOUNT az effektek után a meglévő sztereó különbséget növeli; monó jelből nem készít sztereót. Az oszcillátor WIDTH korábban hat. Széles hangoknál monóban is ellenőrizz. A belső csúcsvédelem nem garantálja, hogy a DAW további effektjei vagy összeadott sávjai sem fognak túlvezérelni.')]),
('Szűrő, burkolók és scope',[
('FILTER','Választható Low Pass 12, Low Pass 24, High Pass 12 és Band Pass 12. A CUTOFF a szűrő frekvenciája, a RES kiemeli annak környezetét, a DRIVE karaktert ad. A FILTER MIX a szűrés arányát adja: nullán a cutoff állítása nem feltétlenül hallható. A KEY TRACK a hangmagassághoz köti a cutoffot. A kijelzett görbe a szűrőbeállítás szemléltetése.'),
('Két burkológörbe','Az AMP ENV a hang hangerejének időbeli lefutása. A: felfutási idő, D: lecsengés a kitartási szintig, S: kitartási szint, R: elengedés utáni lecsengés. A FILTER ENV külön ADSR-rel és AMOUNT-tal mozgatja a szűrőt. Pozitív amount nyitja, negatív az ellenkező irányba viszi. Rövid decay és alacsony sustain pluckhoz, hosszabb attack és release padhoz hasznos.'),
('Valós idejű hullámforma','Az AMP ENV alatti zöld scope az összegzett hangjel effektek, master szélesítés és kimeneti erősítés előtti alakját mutatja. Vízszintesen az idő halad; a középvonal nulla amplitúdó, nem 0 Hz. A rács és a stabilizált kirajzolás segíti az olvasást. A kijelzés automatikusan méretezi az amplitúdót, ezért nem hitelesített hangerőmérő.'),
('A görbe értelmezése','Egy periodikus hang könnyebben olvasható, mint egy detune-os akkord vagy zaj; ezek összetett mozgó görbéje természetes. A kijelző összekeveri a két sztereó oldalt, így a kioltás kisebb görbét okozhat. Az OUTPUT vagy a delay változtatása nem jelenik meg ezen az effektek előtti képen. A scope csak szemléltet, a hallható hangot nem módosítja.')]),
('Effektek',[
('Sorrend','A hangjel Chorus, Delay, majd Reverb feldolgozáson halad át, ezután következik a master szélesítés és kimenet. A MAIN FX szekciója gyors kezelést ad, a részletekhez válaszd a megfelelő effektet az ADVANCED nézetben. A hallható hatáshoz kapcsold be és emeld a MIX értékét.'),
('Chorus','Modulált késleltetéssel vastagít és mozgat. A MIX az eredeti és effektezett hang aránya, a RATE a mozgás sebessége, a DEPTH annak mértéke. Stabil leadhez mérsékelt keverés és lassú rate jó kiindulás; túl nagy depth már feltűnő hangmagasságmozgást adhat.'),
('Delay','A MIX a visszhang aránya. Szabad módban TIME milliszekundumban állítható; tempószinkronban a DIVISION és a DAW tempója adja az időzítést. A FEEDBACK az ismétlődések tartósságát, a TONE a hangszínüket alakítja. A Stereo és Ping Pong eltérő térbeli ismétlést ad. Ha a következő frázist elfedik a visszhangok, csökkentsd a mixet és a feedbacket.'),
('Reverb','A MIX hozzákeveri a zengetést. A SIZE a tér karakterét, a DECAY a lecsengés idejét, a DAMPING a magas tartomány lecsengését alakítja. Ritmikus pluckhoz rövidebb, halkabb zengetés, padhoz nagyobb tér lehet jó. Hosszú release, delay és reverb a billentyű elengedése után is szólhat; ez önmagában nem beragadt hang.')]),
('Előadás és arpeggiator',[
('Hangmódok és glide','A Poly akkordokat játszik, legfeljebb 16 szintihanggal. A Mono és Legato egyszólamú játékmód; a Legato összekötött dallamhoz illik. A GLIDE a hangmagasságok közti átmenet. Módja szerint mindig vagy csak átfedő hangoknál működik. A PITCH BEND tartománya 24 félhangig állítható, a MOD DEPTH a modulációs kerék beépített cutoff-hatását szabályozza.'),
('Arpeggio indítása','Kapcsold be az ARP-ot, és tarts le egy akkordot. Az ORDER: Up, Down, Up/Down, Random vagy Played. A Played a lenyomás sorrendjét követi. A RATE a lépéshossz, az OCTAVES 1-4 oktávra bővíti a mintát. A GATE a lépésen belüli hanghossz, a SWING felváltva hosszabb és rövidebb lépéseket ad.'),
('HOLD','A HOLD a billentyűk elengedése után is megtartja az akkordot. Miután minden fizikai billentyűt elengedtél, az új akkord lecseréli a megtartott frázist. A HOLD kikapcsolásával megszűnik ez a megtartás, de a sustain pedál még befolyásolhatja a hangokat. ARP nélkül visszatérsz a szokásos játékhoz.'),
('Tempóviselkedés','Az első lenyomott hang indítja a frázist. Az arp követi a DAW BPM-jét, de nem a dal abszolút ütemrácsához igazodó szekvenszer. Álló lejátszásnál is használható; futó DAW megállítása törli a frázist, új hang újraindítja. A létrehozott hangok a SAWSTAR-t vezérlik; ez nem MIDI-kimeneti vagy programozható lépésszekvenszer-funkció.')]),
('LFO és moduláció',[
('Két független LFO','Az LFO 1 / LFO 2 azt választja, melyiket szerkeszted; mindkettő egyszerre működhet. Hullámformák: Sine, Triangle, Ramp, Square. A RATE szabad frekvenciát vagy tempószinkron osztást használ. Retrigger esetén az első billentyű újraindítja a fázist, szabad fázisnál folyamatos a mozgás. Közvetlen cél lehet cutoff, pitch, hangerő vagy pan; az AMOUNT ennek mélységét adja.'),
('Négy modulációs sor','Minden sor forrásból, célból és előjeles amountból áll. Forrás: Off, LFO 1, LFO 2, Mod Wheel, Velocity, Aftertouch. Cél: Filter Cutoff, Pitch, Amp Level, Pan, Noise Color. Negatív amount fordítja az irányt. Az Aftertouch MIDI csatornanyomás; polifonikus billentyűnyomás és MPE itt nincs.'),
('Kettős moduláció elkerülése','A mátrix LFO-forrása a közvetlen AMOUNT előtti jel. Ezért az AMOUNT nullázása nem kapcsol ki egy aktív mátrixsort. A több út hatása összeadódik. A MOD DEPTH külön beépített kerék-cutoff kapcsolat: akkor is működik, ha minden mátrixsor Off. Lent a kerék nulla cutoff-emelést ad; ez a preset alapállapota, nem hibás vagy hiányos hang. Feltolva a MOD DEPTH szerint nyitja a szűrőt. A Mod Wheel mátrixsor hatása ehhez hozzáadódik. Nullázd a MOD DEPTH értékét, ha kizárólag a mátrixban szeretnéd kiosztani a kerék hatását.'),
('Kivezérlésmérő','A sztereó mintacsúcs-mérő egy másodpercig tartja a csúcsot. A CLIP a 0 dBFS-t elérő kimeneti mintákat jelzi. Kattintással törölhető, vagy az utolsó túlvezérlés után öt másodperccel kialszik. A kimeneti védelem normálisan megelőzi a clippinget. Ez nem RMS- vagy true-peak mérés.'),
('Finom padmozgás','Válassz padot. Az LFO 2 legyen lassú sine, közvetlen AMOUNT nullával. Egy mátrixsorban válassz LFO 2, Pan és kis pozitív amount értéket. Hallgasd sztereóban, majd csökkentsd az amountot összehasonlításhoz. Save As segítségével új user presetként őrizheted meg.')]),
('Presetek kezelése',[
('Böngészés és magyarázat','A presetsorra kattintás betölti a hangot. A kategória és keresés önmagában csak szűri a listát. A keresés névre, kategóriára és címkékre működik. A szív kedvencet jelöl. A HOW IT WORKS a mentett állapotot mutatja, nem a még el nem mentett módosításokat; mentés után frissül.'),
('Save és Save As','A Save megerősítés után felülírja az aktív, módosított user presetet. A factory és template hangok írásvédettek: Save As készít saját másolatot. A Save As név- és fájlválasztó ablakból új .sawstar fájlt készít; létező fájlnál válassz másik nevet. Külső helyre mentéskor lehetőség szerint könyvtári másolat is készül, de névütközés ezt megakadályozhatja.'),
('Import, Copy és Paste','Az Import egyszerre több .sawstar fájlt fogad, így nem kell egyesével betölteni a gyűjteményt. Jelzi a kihagyott vagy hibás fájlokat, és nem indít el automatikusan hangszínt. A Copy/Paste a szerkesztőn belül másol hangbeállítást; mentésig nem készít fájlt. Ez a vágólap átmeneti, az editor bezárásakor törlődik.'),
('Rename, Delete és Initialize','A Rename a kijelölt user preset nevét módosítja. A Delete megerősítést kér és .deleted biztonsági másolatot hagy; az éppen szóló hangot nem állítja le. Az Initialize megerősítés után Initre állít. Betöltés vagy inicializálás előtt mentsd, amit meg akarsz tartani.'),
('Könyvtár és visszaállítás','User mappa: macOS ~/Library/Application Support/SAWSTAR/Presets ; Windows %APPDATA%\\SAWSTAR\\Presets . A Save mentései az alatta lévő .sawstar-backups mappába kerülnek. Visszaállításhoz másold a mentést a könyvtárba még nem használt .sawstar néven. A DAW projekt külön tárolja a hangparamétereket, de a user fájlhoz tartozó Save kapcsolat nem feltétlenül áll vissza; ehhez töltsd újra a user presetet.')]),
('Factory könyvtár: 24 kiindulópont',[
('Hét Templates hang','Init • Pad-Init • Lead-Init • Pluck-Init • Bass-Init • Keys-Init • Arp-Init. Ezek tudatos kiindulópontok, nem kész bemutatóhangok. Az effektek és mozgások kikapcsoltak. Az Arp-Init esetén is magad kapcsold be az ARP-ot a minta kidolgozásához.'),
('Lead hangok','Wide Saw Lead • SuperSaw One • Silk Lead • Solid Saw Lead. Sztereó unisonhoz, testes saw rétegekhez és összekötött dallamjátékhoz. A Lead-Inithez hasonlítva könnyebb megérteni, miből születik a kész karakter.'),
('Pad hangok','Soft Pad • Soft Pad One • Warm Horizon • Velvet Pad. Kitartott akkordokon hallgasd a burkolók fejlődését és lecsengését. Szélesítés és reverb közben hagyj helyet a többi hangszernek is.'),
('Pluck, basszus és keys','Pluck: Saw Pluck • Glass Pluck • Trance Pluck. Basszus: Deep Bass • Round Sub. Keys: Bright Keys • Air Keys. Próbálj rövid és hosszú hangokat, különböző leütési erősséggel, hogy megismerd a burkolók válaszát.'),
('Arpeggiált hangok','Simple Steps • Octave Steps. Tarts le akkordot, és először a rate/gate hatását vizsgáld. Az üres kategória nem telepítési hiba: ebben a változatban a fenti 24 factory hang szerepel. A saját user presetek ezen felül jelennek meg, nem tartoznak a beépített darabszámba.')]),
('Három hangkészítési gyakorlat',[
('Széles lead','Töltsd be a Lead-Initet. OSC 1-en válassz Saw-t, fokozatosan emeld az UNISON-t, mérsékelt DETUNE mellett. OSC 2-t halkabban keverd hozzá a testességhez. Állíts WIDTH-ot, monóban is ellenőrizve. Az amp attack legyen gyors, a release ne mossa össze túlságosan a frázisokat. Adj kevés delayt, majd más hangszerhez mérve állíts kimeneti szintet. Save As saját néven.'),
('Lágy pad','Töltsd be a Pad-Initet. Keverj két oszcillátort, hosszabbítsd az amp attackot és release-t. Aktív FILTER MIX mellett csökkents cutoffot, adj enyhe filter-envelope amountot. Kevés chorus és reverb következhet. Ha szükséges, használj nagyon lassú, kis mélységű pan vagy cutoff LFO-t. A mozgás nem kötelező: a stabil pad is jó hangszín.'),
('Tiszta pluck','Töltsd be a Pluck-Initet. Rövid filter-envelope decay, alacsony sustain és pozitív amount legyen a kiindulás. Az amp burkolót igazítsd a kívánt hanghosszhoz. Halk tempószinkron delay és kevés reverb mellett megmarad a támadás. Mentés előtt a dal tempójában is próbálj ismétlődő hangokat.'),
('Tisztességes összehasonlítás','A hangosabb változat jobb hangnak tűnhet anélkül, hogy valóban jobb lenne. Hasonló kimeneti szinten hasonlíts. Egyszerre egy szekciót módosíts, mentsd a hasznos változatokat, és a HOW IT WORKS segítségével térj vissza a mentett jelút döntéseihez.')]),
('Hibaelhárítás és támogatás',[
('Nincs hang','Ellenőrizd a DAW hangkimenetét, a sáv útvonalát és monitorozását, a mixer forrásait és az OUTPUT-ot. Egyszerű billentyűpróbához kapcsold ki az ARP/HOLD funkciót. Teljes filter mix és nagyon alacsony cutoff erősen halkíthat. Próbáld az Init vagy egy ismert factory hang betöltését.'),
('Nem hallható egy vezérlő hatása','Ellenőrizd a kapcsolódó kapcsolót és MIX-et. A DETUNE és WIDTH kevéssé hallható, ha a unison oldalsó hangjai nincsenek hozzákeverve. A WIDE sztereó tartalmat igényel. A scope az effektek előtti jelet, a HOW IT WORKS a mentett állapotot mutatja. Az LFO közvetlen nulla amount mellett is hathat mátrixsoron keresztül.'),
('Tovább szól a hang','Nézd meg az amp release-t, sustain pedált, ARP HOLD-ot, delay feedbacket és reverb decayt. Ha ezek megszüntetése után is váratlanul szól, állítsd le a lejátszást, és tesztprojektben töltsd újra a hangszert. Jelentsd a pontos presetet, MIDI eseménysort, DAW-ot és buildadatokat; ne egy fontos projektet írj felül kísérletezés közben.'),
('Preset- vagy megjelenítési gond','Hiányzó presetnél töröld a keresést és kategóriaszűrést. Projektből visszatérés után a Save kapcsolathoz szükség lehet a user preset újratöltésére. Ha nem fér el az ablak, próbálj más GUI méretet. Frissítés után nyisd újra és ellenőrizd az About buildet. Hibás vagy ütköző importfájl kimaradhat; olvasd el az import eredményét.'),
('Projekt és készítő','SAWSTAR: Simple Synth - Big Sound. The Sounds of Trance. Készítő: Gyuricza Róbert / RobCZart82. Forráskód és hibajelzés: https://github.com/RobCZart82/SAWSTAR . A projekt licence és a külső összetevők jogi tájékoztatói a repositoryban találhatók. A letölthető csomagokat és a rendszerkövetelményeket a kiadási jegyzetekben találod.')])]


EN.append(('Performance details',[
('Mono and Legato','These modes select one note using last-note priority; physically held keys take priority over sustain-latched keys. Releasing the selected key may return to an older held key. Changing voice mode starts a new key phrase; release and play the keys again. A short pitch return can be audible and is not proof of a corrupt preset.'),
('LFO retrigger and event order','Retrigger restarts the global LFO when a first key arrives. Same-time MIDI events retain their incoming order. Note Off then Note On can restart the LFO, while overlapping Note On then Note Off can preserve its phase. Free phase avoids this retrigger distinction. This behavior is retained for compatibility.'),
('MIDI reset messages','CC121 resets pitch bend, modulation wheel and channel pressure and releases sustain on its channel; controller smoothing can take time to settle. CC120 stops sound on its channel but preserves wheel and bend values. Sending CC120 on all 16 channels also clears shared effect tails. A new note can then start normally. CC123 releases notes; sustain and release tails can still matter.'),
('Live edits and tails','Changing envelope times during playback affects the active sound. Preset or effect changes can also change an existing tail; compare sounds after the previous tail has finished. Save valuable sounds before changing presets.'),
('Meter and update checks','CLIP observes protected output samples, not overload inside an earlier processing stage. It is not an inter-sample true-peak indicator. After updating, check the About version in the actual host. The screenshots in this guide retain their original 1.0.1 capture labels. Installation and removal details: github.com/RobCZart82/SAWSTAR/blob/main/docs/INSTALLATION.md')]))
HU.append(('Játék és vezérlők',[
('Mono és Legato','Ezekben a módokban egyszerre egy hang szól, az utoljára lenyomott hang elsőbbségével. A ténylegesen tartott billentyű előnyt élvez a pedállal megtartotthoz képest. Az aktuális billentyű elengedése egy korábban tartott hangra léphet vissza. A hangmódváltás új billentyűfrázist indít: engedd el, majd játszd újra a hangokat. Egy rövid hangmagasság-visszalépés hallhatósága önmagában nem sérült preset jele.'),
('LFO és eseménysorrend','Retrigger módban az első billentyű újraindítja a globális LFO-t. Az azonos idejű MIDI-események megőrzik érkezési sorrendjüket. A Note Off, majd Note On újraindíthatja az LFO-t, míg az átfedő Note On, majd Note Off megőrizheti a fázist. Free phase módban nincs ilyen újraindítás. A kompatibilitás érdekében ez a viselkedés megmarad.'),
('MIDI reset üzenetek','A CC121 az adott csatornán alaphelyzetbe állítja a pitch bend, mod wheel és csatornanyomás értékét, és elengedi a sustaint. A simítás miatt a hangbeli változás nem feltétlenül azonnali. A CC120 elnémítja a csatorna hangjait, de megőrzi a kerékértékeket. Mind a 16 csatornára küldött CC120 a közös effektlecsengéseket is törli. Ezután új hang indítható. A CC123 hangelengedés; a sustain és release továbbra is számíthat.'),
('Élő szerkesztés','Lejátszás közben a burkolóidők módosítása az aktív hangot is befolyásolja. Preset- vagy effektváltás a már futó lecsengést is megváltoztathatja. Összehasonlításhoz várd meg az előző hang lecsengését. Presetváltás előtt mentsd az értékes beállításokat.'),
('Mérés és frissítés','A CLIP a védett kimeneti mintákat figyeli, nem a korábbi fokozatok belső túlvezérlését. Nem true-peak jelzés. Frissítés után a DAW-ban megnyitott About ablak verzióját ellenőrizd. A kézikönyv képein megmaradtak az eredeti 1.0.1 felvételi címkék. Telepítés és eltávolítás: github.com/RobCZart82/SAWSTAR/blob/main/docs/INSTALLATION.md')]))

def footer(c,d):
 c.setStrokeColor(colors.HexColor('#b8d4e1'));c.line(45,42,550,42)
 c.setFont('DV',8);c.setFillColor(colors.HexColor('#526573'));c.drawString(45,28,f'SAWSTAR | {EDITION_LABEL} | {EDITION}');c.drawRightString(550,28,str(d.page))
def build(lang,pages):
 out=ROOT/f'output/pdf/SAWSTAR-User-Manual-{lang}.pdf'
 doc=SimpleDocTemplate(str(out),pagesize=(595.28,841.89),rightMargin=45,leftMargin=45,topMargin=43,bottomMargin=58,title='SAWSTAR '+('User Manual' if lang=='EN' else 'Használati útmutató'),author='SAWSTAR / Gyuricza Róbert')
 story=[]
 for ix,(title,sections) in enumerate(pages):
  if ix:story.append(PageBreak())
  if ix==0:
   story.append(Paragraph('SAWSTAR',S['Title2']))
   story.append(Paragraph('User Manual' if lang=='EN' else 'Használati útmutató',S['Sub']))
   story.append(Paragraph('Simple Synth - Big Sound<br/>The Sounds of Trance',S['Small2']))
   story.append(Image(str(ROOT/'tmp/pdfs/main.png'),width=505,height=300))
  else: story.append(Paragraph(f'{ix+1:02d} / {title}',S['Title2']))
  for heading,body in sections:
   story.append(KeepTogether([Paragraph(heading,S['Sub']),Paragraph(body,S['Body'])]))
  if ix in (2,9):
   story.append(Spacer(1,14))
   story.append(Image(str(ROOT/('tmp/pdfs/advanced.png' if ix==2 else 'tmp/pdfs/presets.png')),width=370,height=220))
 doc.build(story,onFirstPage=footer,onLaterPages=footer)
 print(out)
for lang,pages in [('EN',EN),('HU',HU)]:build(lang,pages)
