# SPDX-License-Identifier: MIT
# Shared by the plugin build and standalone metadata regression tests.
string(JSON _candidate GET "${SAWSTAR_METADATA}" candidate)
string(JSON _date ERROR_VARIABLE _date_error GET "${SAWSTAR_METADATA}" release_date)
if(_date_error)
  set(_date "")
endif()
if(NOT _candidate MATCHES "^(dev|rc[0-9]+)?$")
  message(FATAL_ERROR "Invalid SAWSTAR candidate: ${_candidate}")
endif()
if(_candidate AND _date)
  message(FATAL_ERROR "Development/candidate builds must not carry a release date")
endif()
if(_date)
  if(NOT _date MATCHES "^[0-9][0-9][0-9][0-9]\\.[0-9][0-9]\\.[0-9][0-9]\\.$")
    message(FATAL_ERROR "SAWSTAR release_date must use YYYY.MM.DD.")
  endif()
  set(SAWSTAR_DISPLAY_VERSION "${PROJECT_VERSION}")
  set(SAWSTAR_DATE_LABEL "Release")
  set(SAWSTAR_BUILD_DATE "${_date}")
else()
  if(_candidate)
    set(SAWSTAR_DISPLAY_VERSION "${PROJECT_VERSION} ${_candidate}")
  else()
    set(SAWSTAR_DISPLAY_VERSION "${PROJECT_VERSION} Pre Release")
  endif()
  set(SAWSTAR_DATE_LABEL "Build")
  string(TIMESTAMP SAWSTAR_BUILD_DATE "%Y.%m.%d." UTC)
endif()
